import { ThemeProvider } from "@/components/providers/theme-provider";
import "@/styles/globals.css";

import { ModeToggle } from "@/components/ui/darkModeToggle";
import { Inter } from "next/font/google";
import { SideBar } from "@/components/ui/sidebar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "STRATASKY",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex w-full border-b border-slate-400 p-5">
              <SideBar />
              <span className="ml-auto">
                <ModeToggle />
              </span>
              {children}
            </div>
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
